version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
      - "16000:16000"
    expose:
      - 4001
      - 16000
    volumes:
      - ./.env:/opt/app/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: "tilt"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
