version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: always
    profiles:
      - prod
    ports:
      - "4001:4001"
      - "16000:16000"
    expose:
      - 4001
      - 16000
    volumes:
      - ./.env:/app/.env
    depends_on:
      - postgres

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    container_name: dev
    profiles:
      - dev
    ports:
      - "4001:4001"
      - "16000:16000"
    expose:
      - 4001
      - 16000
    volumes:
      - ./.env:/app/.env
      - ./src:/app/src/
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    profiles:
      - dev
      - prod
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: "tilt"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
